# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/caio.gmunhoz@gmail.com/weather-lakehouse/src/pipelines/gold")

# COMMAND ----------

SILVER_PATH = 'weather_lakehouse.silver'

silver_forecasts = spark.read.table(f'{SILVER_PATH}.forecasts')
silver_observations = spark.read.table(f'{SILVER_PATH}.observations')
weather_foo = spark.read.table('weather_lakehouse.gold.fact_weather_hourly')

# COMMAND ----------

display(silver_forecasts.join(silver_observations, ['latitude', 'longitude', 'time']))

# COMMAND ----------

silver_forecasts.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC
