# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `weather_lakehouse`")
spark.sql("USE SCHEMA `landing`")

# COMMAND ----------

from pyspark.sql.types import (
    StructType, StructField, DoubleType, 
    IntegerType, StringType, ArrayType
)

RAW_SCHEMA = StructType([
    StructField('latitude', DoubleType(), False),
    StructField('longitude', DoubleType(), False),
    StructField('generationtime_ms', DoubleType(), False),
    StructField('utc_offset_seconds', IntegerType(), False),
    StructField('timezone', StringType(), False),
    StructField('timezone_abbreviation', StringType(), False),
    StructField('elevation', DoubleType(), False),
    StructField(
        'hourly_units',
        StructType([
            StructField('time', StringType(), False),
            StructField('temperature_2m', StringType(), False),
            StructField('precipitation', StringType(), False),
            StructField('apparent_temperature', StringType(), False),
            StructField('cloud_cover', StringType(), False)
        ]),
        False
    ),
    StructField(
        'hourly',
        StructType([
            StructField('time', ArrayType(StringType()), False),
            StructField('temperature_2m', ArrayType(DoubleType()), False),
            StructField('precipitation', ArrayType(DoubleType()), False),
            StructField('apparent_temperature', ArrayType(DoubleType()), False),
            StructField('cloud_cover', ArrayType(IntegerType()), False)
        ]),
        False
    )
])

# COMMAND ----------

raw1 = (
    spark.read
    .schema(RAW_SCHEMA)
    .option('multiLine', True)
    .json('/Volumes/weather_lakehouse/landing/forecasts/2022-2025.json')
)

# COMMAND ----------

display(raw1)

